version: '3'
services:
    
    frontend:  
        build: 
            context: ./src/frontend/
            dockerfile: ../../docker/vuejs/Dockerfile
        ports:
            - 13000:13000
        command: [sh, -c, npm install --verbose && npm run dev]
        volumes:
            - "./src/frontend:/app"
        stdin_open: true
        tty: true

    db:
        image: mysql:5.7.22
        volumes:
              - ./db/mysql_data:/var/lib/mysql
        ports:
             - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: test

    backend:
        build: 
            context: ./src/backend/
            dockerfile: ../../docker/rails/Dockerfile

        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        environment:
          DB_HOST_NAME: db
          IDM_READER_HOST_NAME: '10.200.10.1:3005'
        volumes:
            - "./src/backend:/rails"
        ports:
            - "3000:3000"
        depends_on:
            - db
        links:
            - db
